package jp.co.scraper.newemployees.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 部署マスタ モデルクラス.
 *
 * @author user, generated by ERMaster
 */
public class Department implements Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** id */
    private Integer id;

    /** 事業部マスタ */
    private Division division;

    /** 部署名 */
    private String name;

    /** 削除フラグ */
    private Boolean deleteFlg;

    /** 登録日 */
    private Date created;

    /** 更新日 */
    private Date modified;

    /** 部課マスタ 一覧 */
    private List<Section> sections;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the division
     */
    public Division getDivision() {
        return division;
    }

    /**
     * @param division the division to set
     */
    public void setDivision(Division division) {
        this.division = division;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the deleteFlg
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * @param deleteFlg the deleteFlg to set
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * @return the created
     */
    public Date getCreated() {
        return created;
    }

    /**
     * @param created the created to set
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * @return the modified
     */
    public Date getModified() {
        return modified;
    }

    /**
     * @param modified the modified to set
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * @return the sections
     */
    public List<Section> getSections() {
        return sections;
    }

    /**
     * @param sections the sections to set
     */
    public void setSections(List<Section> sections) {
        this.sections = sections;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Department ["
                + "id=" + id
                + ", division=" + division
                + ", name=" + name
                + ", deleteFlg=" + deleteFlg
                + ", created=" + created
                + ", modified=" + modified
                + ", sections=" + sections
                + "]";
    }
}
