package jp.co.scraper.newemployees.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 事業部マスタ モデルクラス.
 *
 * @author user, generated by ERMaster
 */
public class Division implements Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** id */
    private Integer id;

    /** 事業部名 */
    private String name;

    /** 削除フラグ */
    private Boolean deleteFlg;

    /** 登録日 */
    private Date created;

    /** 更新日 */
    private Date modified;

    /** 部署マスタ 一覧 */
    private List<Department> departments;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the deleteFlg
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * @param deleteFlg the deleteFlg to set
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * @return the created
     */
    public Date getCreated() {
        return created;
    }

    /**
     * @param created the created to set
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * @return the modified
     */
    public Date getModified() {
        return modified;
    }

    /**
     * @param modified the modified to set
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * @return the departments
     */
    public List<Department> getDepartments() {
        return departments;
    }

    /**
     * @param departments the departments to set
     */
    public void setDepartments(List<Department> departments) {
        this.departments = departments;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Division ["
                + "id=" + id
                + ", name=" + name
                + ", deleteFlg=" + deleteFlg
                + ", created=" + created
                + ", modified=" + modified
                + ", departments=" + departments
                + "]";
    }
}
