package jp.co.scraper.newemployees.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 社員紹介テーブル モデルクラス.
 *
 * @author user, generated by ERMaster
 */
public class Profile implements Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** id */
    private Integer id;

    /** 部課マスタ */
    private Section section;

    /** 入社月テーブル */
    private EnterMonth enterMonth;

    /** 画像テーブル */
    private Image image;

    /** 名字 */
    private String lastName;

    /** 名前 */
    private String firstName;

    /** 名字かな */
    private String lastNameKana;

    /** 名前かな */
    private String firstNameKana;

    /** 趣味 */
    private String hobby;

    /** 経歴 */
    private String career;

    /** 自己PR */
    private String selfPr;

    /** 備考 */
    private String remarks;

    /** 削除フラグ */
    private Boolean deleteFlg;

    /** 登録日 */
    private Date created;

    /** 更新日 */
    private Date modified;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the section
     */
    public Section getSection() {
        return section;
    }

    /**
     * @param section the section to set
     */
    public void setSection(Section section) {
        this.section = section;
    }

    /**
     * @return the enterMonth
     */
    public EnterMonth getEnterMonth() {
        return enterMonth;
    }

    /**
     * @param enterMonth the enterMonth to set
     */
    public void setEnterMonth(EnterMonth enterMonth) {
        this.enterMonth = enterMonth;
    }

    /**
     * @return the image
     */
    public Image getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the lastName to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the firstName to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the lastNameKana
     */
    public String getLastNameKana() {
        return lastNameKana;
    }

    /**
     * @param lastNameKana the lastNameKana to set
     */
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    /**
     * @return the firstNameKana
     */
    public String getFirstNameKana() {
        return firstNameKana;
    }

    /**
     * @param firstNameKana the firstNameKana to set
     */
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    /**
     * @return the hobby
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * @param hobby the hobby to set
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * @return the career
     */
    public String getCareer() {
        return career;
    }

    /**
     * @param career the career to set
     */
    public void setCareer(String career) {
        this.career = career;
    }

    /**
     * @return the selfPr
     */
    public String getSelfPr() {
        return selfPr;
    }

    /**
     * @param selfPr the selfPr to set
     */
    public void setSelfPr(String selfPr) {
        this.selfPr = selfPr;
    }

    /**
     * @return the remarks
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * @param remarks the remarks to set
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * @return the deleteFlg
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * @param deleteFlg the deleteFlg to set
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * @return the created
     */
    public Date getCreated() {
        return created;
    }

    /**
     * @param created the created to set
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * @return the modified
     */
    public Date getModified() {
        return modified;
    }

    /**
     * @param modified the modified to set
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Profile ["
                + "id=" + id
                + ", section=" + section
                + ", enterMonth=" + enterMonth
                + ", image=" + image
                + ", lastName=" + lastName
                + ", firstName=" + firstName
                + ", lastNameKana=" + lastNameKana
                + ", firstNameKana=" + firstNameKana
                + ", hobby=" + hobby
                + ", career=" + career
                + ", selfPr=" + selfPr
                + ", remarks=" + remarks
                + ", deleteFlg=" + deleteFlg
                + ", created=" + created
                + ", modified=" + modified
                + "]";
    }
}
