package jp.co.scraper.newemployees.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 部課マスタ モデルクラス.
 *
 * @author user, generated by ERMaster
 */
public class Section implements Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** id */
    private Integer id;

    /** 部署マスタ */
    private Department department;

    /** 部課名 */
    private String name;

    /** 削除フラグ */
    private Boolean deleteFlg;

    /** 登録日 */
    private Date created;

    /** 更新日 */
    private Date modified;

    /** 社員紹介テーブル 一覧 */
    private List<Profile> profiles;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the department
     */
    public Department getDepartment() {
        return department;
    }

    /**
     * @param department the department to set
     */
    public void setDepartment(Department department) {
        this.department = department;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the deleteFlg
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * @param deleteFlg the deleteFlg to set
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * @return the created
     */
    public Date getCreated() {
        return created;
    }

    /**
     * @param created the created to set
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * @return the modified
     */
    public Date getModified() {
        return modified;
    }

    /**
     * @param modified the modified to set
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * @return the profiles
     */
    public List<Profile> getProfiles() {
        return profiles;
    }

    /**
     * @param profiles the profiles to set
     */
    public void setProfiles(List<Profile> profiles) {
        this.profiles = profiles;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Section ["
                + "id=" + id
                + ", department=" + department
                + ", name=" + name
                + ", deleteFlg=" + deleteFlg
                + ", created=" + created
                + ", modified=" + modified
                + ", profiles=" + profiles
                + "]";
    }
}
